# Generated by Django 4.2 on 2023-04-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categoria_marca_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='caballos',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio',
        ),
        migrations.CreateModel(
            name='subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.categoria')),
            ],
        ),
    ]
