# Generated by Django 4.2 on 2023-04-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_vehiculo_caballos_remove_vehiculo_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.subcategoria'),
            preserve_default=False,
        ),
    ]
