# Generated by Django 4.2 on 2023-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_vehiculo_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='Descripcion',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='caballos',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio',
            field=models.IntegerField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
