# Generated by Django 4.2 on 2023-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_vehiculo_descripcion_vehiculo_caballos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='caballos',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.CharField(max_length=15),
        ),
    ]
