# Generated by Django 4.2 on 2023-04-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_vehiculo_caballos_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='Nombre',
            field=models.CharField(max_length=20),
        ),
    ]
