# Generated by Django 4.2 on 2023-04-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_subcategoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
