# Generated by Django 4.2 on 2023-05-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_profile_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Imagen',
            field=models.ImageField(default=1, upload_to='users-profile'),
            preserve_default=False,
        ),
    ]
