# Generated by Django 4.2 on 2023-05-16 04:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='nombre'),
            preserve_default=False,
        ),
    ]
